name: files
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  handy_window: ^0.3.1
  xdg_icons: ^0.0.1
  yaru: ^0.5.6
  yaru_icons: ^1.0.3
  yaru_widgets: ^2.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
