name: files
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  handy_window: ^0.1.7
  xdg_icons: ^0.0.1
  yaru: ^0.4.3
  yaru_icons: ^0.2.6
  yaru_widgets:
    git:
      url: https://github.com/ubuntu/yaru_widgets
      ref: ba5e298fc1b0737ca5d8eca2f087c6da1dd99389

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
